version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
